# Generated by Django 4.0.3 on 2022-05-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomEstable', models.CharField(max_length=50)),
                ('descripcion_Estable', models.CharField(max_length=250)),
                ('sitio_web', models.URLField()),
                ('latitud', models.CharField(max_length=20)),
                ('longitud', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=10)),
                ('whatsapp', models.CharField(max_length=10)),
            ],
        ),
    ]
