# Generated by Django 4.0.3 on 2022-05-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_perfil_latitud_alter_perfil_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='latitud',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='longitud',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
