# Generated by Django 4.0.3 on 2022-05-28 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_alter_perfil_latitud_alter_perfil_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='latitud',
            field=models.DecimalField(decimal_places=18, max_digits=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='longitud',
            field=models.DecimalField(decimal_places=18, max_digits=20),
        ),
    ]
