# Generated by Django 4.0.3 on 2022-05-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_perfil_categoria_alter_perfil_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='sitio_web',
            field=models.URLField(blank=True, null=True),
        ),
    ]
