# Generated by Django 4.0.3 on 2022-05-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0007_perfil_imagen_alter_perfil_sitio_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(upload_to='perfiles'),
        ),
    ]
