# Generated by Django 4.0.3 on 2022-05-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0008_alter_perfil_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='entrada',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='salida',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
