# Generated by Django 4.0.3 on 2022-06-07 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0012_alter_perfil_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='slug',
        ),
    ]
